---
include:
  - board: ergohaven
    shield: velvet_v3_ui_left
    keymap: velvet_v3_ui_one
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_ui_one_left-ergohaven-zmk

  - board: ergohaven
    shield: velvet_v3_ui_right
    keymap: velvet_v3_ui_one
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_ui_one_right-ergohaven-zmk
